config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    get "/user/settings",  to: "user_settings#edit", as: "user_settings"
    put "/user/settings",  to: "user_settings#update", as: ""
    delete "/user/settings", to: "user_settings#destroy", as: ""
  end
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :doctor do
    get "/doctor/settings",  to: "doctor_settings#edit", as: "doctor_settings"
    put "/doctor/settings",  to: "doctor_settings#update", as: ""
    delete "/doctor/settings", to: "doctor_settings#destroy", as: ""
  end
  devise_for :doctors, controllers: { registrations: "registrations" }

  root "home#index"
  resources :verifications, only: :create

  resources :doctors, only: %i[index show] do
    resources :appointments, only: %i[new create]
  end

  resources :appointments, only: %i[index show]

  resources :recommendations, only: %i[create]
end

app/views/partials/_alert.haml
.alert.alert-dismissible{role: "alert", class: "alert-#{type}"}
  = msg
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", type: "button"}

app/views/partials/_footer.haml
%footer.text-center.text-lg-start.bg-light.text-muted
  %section.d-flex.justify-content-center.justify-content-lg-between.p-4.border-bottom
    .me-5.d-none.d-lg-block
      %span Get connected with us on social networks:
    %div
      %a.me-4.text-reset{href: ""}
        %i.fa.fa-github
      %a.me-4.text-reset{href: ""}
        %i.fa.fa-google
      %a.me-4.text-reset{href: ""}
        %i.fa.fa-facebook-f
      %a.me-4.text-reset{href: ""}
        %i.fa.fa-twitter
      %a.me-4.text-reset{href: ""}
        %i.fa.fa-instagram
  %section
    .container.text-center.text-md-start.mt-5
      .row.mt-3
        .col-md-3.col-lg-4.col-xl-3.mx-auto.mb-4
          %h6.text-uppercase.fw-bold.mb-4
            %i.fa.fa-gem.me-3>
            Company name
          %p
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
        .col-md-2.col-lg-2.col-xl-2.mx-auto.mb-4
          %h6.text-uppercase.fw-bold.mb-4
            Products
          %p
            %a.text-reset{href: "#!"} Angular
          %p
            %a.text-reset{href: "#!"} React
          %p
            %a.text-reset{href: "#!"} Vue
          %p
            %a.text-reset{href: "#!"} Laravel
        .col-md-3.col-lg-2.col-xl-2.mx-auto.mb-4
          %h6.text-uppercase.fw-bold.mb-4
            Useful links
          %p
            %a.text-reset{href: "#!"} Pricing
          %p
            %a.text-reset{href: "#!"} Settings
          %p
            %a.text-reset{href: "#!"} Orders
          %p
            %a.text-reset{href: "#!"} Help
        .col-md-4.col-lg-3.col-xl-3.mx-auto.mb-md-0.mb-4
          %h6.text-uppercase.fw-bold.mb-4 Contact
          %p
            %i.fa.fa-home.me-3
            New York, NY 10012, US
          %p
            %i.fa.fa-envelope.me-3
            info@example.com
          %p
            %i.fa.fa-phone.me-3
            + 01 234 567 88
          %p
            %i.fa.fa-print.me-3
            + 01 234 567 89

app/views/partials/_head.haml
%head
  %meta{charset: "UTF-8"}
  %meta{name: "viewport", content: "width=device-width"}
  %title 
    = t :app_name
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_pack_tag :application
  = javascript_pack_tag :application

app/views/partials/_header.haml
%header.navbar.bg-light
  .container-fluid
    = link_to t(:app_name), root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "offcanvasNavbar", "data-bs-target" => "#offcanvasNavbar", "data-bs-toggle" => "offcanvas", type: "button"}
      %span.navbar-toggler-icon
    #offcanvasNavbar.offcanvas.offcanvas-end{"aria-labelledby" => "offcanvasNavbarLabel", tabindex: "-1"}
      .offcanvas-header
        %h5#offcanvasNavbarLabel.offcanvas-title
          = t :app_name
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "offcanvas", type: "button"}
      .offcanvas-body
        %ul.navbar-nav.justify-content-end.flex-grow-1.pe-3
          %li.nav-item
            = link_to t('link.to_home'), root_path, class: "nav-link"
          %li.nav-item
            = link_to t('link.to_doctors'), doctors_path, class: "nav-link"
          - if user_signed_in?
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
                = t 'link.to_my_account'
              %ul.dropdown-menu
                %li
                  = link_to t('link.to_my_appointments'), appointments_path, class: "dropdown-item"
                %li
                  = link_to t('link.to_settings'), user_settings_path, class: "dropdown-item"
                %li
                  %hr.dropdown-divider/
                %li
                  = link_to t('link.log_out'), destroy_user_session_path, :method => :delete, class: "dropdown-item"
          - elsif doctor_signed_in?
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
                = t 'link.to_my_account'
              %ul.dropdown-menu
                %li
                  = link_to t('link.to_my_appointments'), appointments_path, class: "dropdown-item"
                %li
                  = link_to t('link.to_settings'), doctor_settings_path, class: "dropdown-item"
                %li
                  %hr.dropdown-divider/
                %li
                  = link_to t('link.log_out'), destroy_user_session_path, :method => :delete, class: "dropdown-item"
          - else
            - unless user_signed_in?
              %li.nav-item.dropdown
                %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
                  = t 'link.user'
                %ul.dropdown-menu
                  %li
                    = link_to t('link.log_in'), new_user_session_path, class: "dropdown-item"
                  %li
                    = link_to t('link.sign_up'), new_user_registration_path, class: "dropdown-item"
            - unless doctor_signed_in?
              %li.nav-item.dropdown
                %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
                  = t 'link.doctor'
                %ul.dropdown-menu
                  %li
                    = link_to t('link.log_in'), new_doctor_session_path, class: "dropdown-item"
                  %li
                    = link_to t('link.sign_up'), new_doctor_registration_path, class: "dropdown-item"

= render("/partials/alert", msg: notice, type: :success) if notice
= render("/partials/alert", msg: alert, type: :danger) if alert

= render "/partials/modal"

app/views/partials/_modal.haml
#staticBackdrop.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-bs-backdrop" => "static", "data-bs-keyboard" => "false", tabindex: "-1"}
  .modal-dialog.modal-dialog-centered