config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    get "/user/settings",  to: "user_settings#edit", as: "user_settings"
    put "/user/settings",  to: "user_settings#update", as: ""
    delete "/user/settings", to: "user_settings#destroy", as: ""
  end
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :doctor do
    get "/doctor/settings",  to: "doctor_settings#edit", as: "doctor_settings"
    put "/doctor/settings",  to: "doctor_settings#update", as: ""
    delete "/doctor/settings", to: "doctor_settings#destroy", as: ""
  end
  devise_for :doctors, controllers: { registrations: "registrations" }

  root "home#index"
  resources :verifications, only: :create

  resources :doctors, only: %i[index show] do
    resources :appointments, only: %i[new create]
  end

  resources :appointments, only: %i[index show]

  resources :recommendations, only: %i[create]
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  attribute :verification_code, :string
  attribute :destroy_confirmation, :boolean

  belongs_to :specialty, optional: true
  has_one :picture, as: :imageable, dependent: :destroy
  has_many :appointments, dependent: :nullify

  accepts_nested_attributes_for :picture

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :phone_number, uniqueness: { case_sensitive: false }
  validates :phone_number, format: { with: /\A\+[0-9]{7,15}\z/,
                                     message: I18n.t("errors.messages.invalide_phone_number") }

  def email_required?; end

  def will_save_change_to_email?; end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  load_and_authorize_resource

  def index
    @pagy, @doctors = pagy_countless(DoctorsQuery.new.call(@doctors, filter_params).decorate,
                                     link_extra: 'data-remote="true"')
  end

  def show
    @doctor = @doctor.decorate
    start_date = params.fetch(:start_date, Time.zone.today).to_date
    @work_hours = WorkScheduleServices::Build.call(@doctor, start_date) if can? :create, Appointment
  end

  private

  def filter_params
    params.permit(:specialty)
  end
end

app/views/doctors/partials/_calendar.haml
= week_calendar(events: @work_hours) do |date, work_hours|
  = date.day
  - work_hours.each do |work_hour|
    .card.text-bg-secondary
      .card-body
        - if work_hour.busy_time
          %a.btn.btn-outline-danger{disabled: true}
            = t '.unavailable_for_reception'
        - else
          = link_to new_doctor_appointment_path(@doctor, 
                                                appointment: { start_time: work_hour.start_time, end_time: work_hour.end_time }),
                    remote: true,
                    "data-bs-target": "#staticBackdrop",
                    "data-bs-toggle": "modal",
                    class: "btn btn-outline-light" do
            = t '.make_an_appointment'
      .card-footer.text-bg-secondary
        %small
          = work_hour.duration_time

app/views/doctors/partials/_doctor.haml
.doctor.card.col-xs-12.col-sm-3
  = link_to doctor do
    = image_tag doctor.image_url, class: "card-img-top"
  .card-body
    %table.table.table-sm
      %tbody
        %tr
          %td{colspan: 2}
            %h5.card-title
              = doctor.full_name
        %tr
          %td
            = t '.specialty'
          %td
            %p.card-text
              = doctor.specialty
        %tr
          %td
            %small.text-muted
              = t '.work_experience'
          %td
            %p.card-text
              %small.text-muted
                = doctor.seniority

app/views/doctors/partials/_doctor_full_info.haml
.card.mb-3.col-12
  .row.g-5
    .col-md-4
      = image_tag @doctor.image_url, class: "card-img-top"
    .col-md-8
      .card-body
        %table.table.table-sm
          %tbody
            %tr
              %td{colspan: 2}
                %h5.card-title
                  = @doctor.full_name
            %tr
              %td
                = t '.specialty'
              %td
                %p.card-text
                  = @doctor.specialty
            %tr
              %td
                = t '.work_experience'
              %td
                %p.card-text
                  = @doctor.seniority
            %tr
              %td
                %small.text-muted
                  = t '.description'
              %td
                %p.card-text
                  %small.text-muted
                    = @doctor.description

app/views/doctors/partials/_filter.haml
.dropdown
  %a.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
    =Specialty.find_by(id: params[:specialty])&.name || t('.all')
  %ul.dropdown-menu
    %li
      = link_to doctors_path, class: 'dropdown-item' do
        = t '.all'
    - specialtys.each do |specialty|
      %li
        = link_to doctors_path(specialty: specialty), class: "dropdown-item" do
          = specialty.name

app/views/doctors/partials/_next_page_link.haml
= raw pagy_next_link(pagy, text: t('.view_more'), link_extra: 'id="more_doctors" class="btn btn-outline-primary"')