config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    get "/user/settings",  to: "user_settings#edit", as: "user_settings"
    put "/user/settings",  to: "user_settings#update", as: ""
    delete "/user/settings", to: "user_settings#destroy", as: ""
  end
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :doctor do
    get "/doctor/settings",  to: "doctor_settings#edit", as: "doctor_settings"
    put "/doctor/settings",  to: "doctor_settings#update", as: ""
    delete "/doctor/settings", to: "doctor_settings#destroy", as: ""
  end
  devise_for :doctors, controllers: { registrations: "registrations" }

  root "home#index"
  resources :verifications, only: :create

  resources :doctors, only: %i[index show] do
    resources :appointments, only: %i[new create]
  end

  resources :appointments, only: %i[index show]

  resources :recommendations, only: %i[create]
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
  has_one :recommendation, dependent: :destroy
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  load_and_authorize_resource param_method: :require_params

  before_action :set_doctor, only: %i[new create]

  def index
    @pagy, @appointments = pagy(@appointments)
    @appointments = @appointments.decorate
  end

  def show
    @appointment = @appointment.decorate
    @appointment.recommendation ? recommendations_viewed : build_recommendation
  end

  def new
    @appointment = @doctor.appointments.new(require_params).decorate
  end

  def create
    @appointment = Appointment.new(user: current_user, doctor: @doctor)
    appointment_form = AppointmentForm.new(@appointment)
    if appointment_form.validate(require_params)
      appointment_form.save
      redirect_to @appointment, notice: t(".success")
    else
      redirect_to doctor_path(@doctor, start_date: @appointment.start_time),
                  alert: ReformErrors.to_human_readable(appointment_form.errors)
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find_by(id: params[:doctor_id])
  end

  def require_params
    params.require(:appointment).permit(:start_time, :end_time, :full_name, :symptoms)
  end

  def recommendations_viewed
    return if !@appointment.recommendation&.unreviewed || doctor_signed_in?

    @appointment.recommendation.update(unreviewed: false)
  end

  def build_recommendation
    return unless can? :create, Recommendation

    Recommendation.new(appointment: @appointment)
  end
end

app/views/appointments/partials/_appointment.haml
%tr
  %td
    = appointment.duration_datetime
  %td
    = appointment.full_name
  - if user_signed_in?
    %td
      = appointment.doctor.full_name
  - if doctor_signed_in?
    %td
      = appointment.user.phone_number
  %td
    = render "appointments/partials/button_show", appointment: appointment

app/views/appointments/partials/_appointment_full_info.haml
%table.table.table-borderless
  %tbody
    %tr
      %td
        = t ".date"
      %td.date
        = @appointment.duration_datetime
    %tr
      %td
        = t ".doctor"
      %td.doctor
        = @appointment.doctor.full_name
    %tr
      %td
        = t ".specialty"
      %td.specialty
        = @appointment.doctor.specialty&.name
    %tr
      %td
        = t ".patient"
      %td.patient
        = @appointment.full_name
    %tr
      %td
        = t ".user_tel"
      %td.user_tel
        = @appointment.user.phone_number
    %tr
      %td
        = t ".symptoms"
      %td.symptoms
        = @appointment.symptoms

app/views/appointments/partials/_button_show.haml
- appointment_completed = present(appointment.object){|appointment| appointment.completed?}
- appointment_unreviewed = present(appointment.object){|appointment| appointment.unreviewed?}

= link_to appointment, class: "btn position-relative btn-outline-#{appointment_completed ? :dark : :secondary}" do
  - if appointment_unreviewed
    %span.position-absolute.top-0.start-100.translate-middle.p-2.bg-secondary.border.border-light.rounded-circle
  = t ".show"

app/views/appointments/partials/_modal_form.haml
.modal-content
  = simple_form_for(@appointment, url: doctor_appointments_path) do |f|
    .modal-header
      #staticBackdropLabel.modal-title
        %h5
          = @appointment.doctor.full_name
          %small.text-muted
            = @appointment.doctor.decorate.specialty
        = @appointment.duration_datetime
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
    .modal-body
      %legend
        = t ".new_appointment"
      .visually-hidden
        = f.input :start_time, as: :datetime, html5: true
        = f.input :end_time, as: :datetime, html5: true
      = f.input :full_name
      = f.input :symptoms
    .modal-footer
      %button.btn.btn-outline-secondary{"data-bs-dismiss" => "modal", type: "button"}
        = t ".close"
      = f.button :submit, t('.submit'), class: "btn-outline-primary"

app/views/appointments/partials/_recommendation.haml
%p.recommendation_body
  = @appointment.recommendation.body
%small.text-muted.recommendation_date
  = @appointment.recommendation.decorate.date

app/views/appointments/partials/_recommendation_form.haml
= simple_form_for(@appointment.recommendation, html: { class: "disabled-submit-btn"}) do |f|
  = f.input :body
  .visually-hidden
    = f.input :appointment_id
  .general-settings-btn.mb-4
    = f.button :submit, t('.submit'), class: "btn-outline-primary", disabled: true